# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_href', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('department_href', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_img', models.CharField(max_length=255)),
                ('product_href', models.CharField(max_length=255, unique=True)),
                ('product_from_price', models.FloatField()),
                ('product_on_sale', models.FloatField()),
                ('product_is_available', models.IntegerField()),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promosite.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('store_href', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='department_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promosite.Store'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promosite.Store'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promosite.Department'),
        ),
    ]
